name: Deploy do Meu Site
 
on: 
  push: 
    branches: 
      - main 
      - master 
  pull_request: 
    branches: 
      - main 
 
jobs: 
  valida-projeto: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout do codigo 
        uses: actions/checkout@v4 
 
      - name: Ver memoria RAM do Runner 
        run: lsb_release -a && free -h 
 
      - name: Ver memória da máquina 
        run: free -h