name: Deploy do Meu Site

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main

jobs:

  validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Explorando o Runner
        run: lsb_release -a

      - name: Ver memoria RAM do Runner
        run: free -h

      - name: Ver quantidade de CPUs
        run: nproc

      - name: Verifica se o index existe
        run: test -f index.html


  instala-ferramenta:
    runs-on: ubuntu-latest

    steps:
      - name: Instala cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Testa cowsay
        run: cowsay "Ferramenta instalada!"


    deploy:
    needs: validacao
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instala cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Testa cowsay
        run: cowsay "Ferramenta instalada no deploy!"

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'